all:
	pdflatex fluid-mechanics-kafi.tex
	pdflatex fluid-mechanics-kafi.tex
	pdflatex fluid-mechanics-kafi.tex

edit:
	geany -i \
	fluid-mechanics-kafi.tex \
	chapters/ch01.tex \
	chapters/ch02.tex \
	chapters/ch03.tex \
	chapters/ch04.tex \

git:
	git add .
	git commit -m "edit"
	git push
	
